name: ssl-ecg-biosignals
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - jupyter
  - pip
  - pip:
    - pre-commit
    - black
    - flake8
    - isort
    - mypy