device: 'mps'
model_type: 'encoder'

paths:
  model_path: '/Users/tenebrissilvam/Code/smiles_2025/ST-MEM/weights/st_mem_vit_base_encoder.pth'
  config_path: '/Users/tenebrissilvam/Code/smiles_2025/ST-MEM/configs/downstream/st_mem.yaml'
  data_path: '/Users/tenebrissilvam/Code/smiles_2025/data/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/records500_processed'
  val_csv: '/Users/tenebrissilvam/Code/smiles_2025/data/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/index_GENERAL_DIAGNOSIS_val.csv'
  train_csv: '/Users/tenebrissilvam/Code/smiles_2025/data/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/index_GENERAL_DIAGNOSIS_train_val.csv'

output:
  embeddings_results: '/Users/tenebrissilvam/Code/smiles_2025/ST-MEM/outs/embeddings_results.csv'
  classification_results: '/Users/tenebrissilvam/Code/smiles_2025/ST-MEM/outs/classification_st_mem_cluster.csv'
