seed: 42
device: mps
output_dir: ./outs
exp_name: encoder_vqvae_ptb_xl_fixed

ddp:
  distributed: false
  dist_url: env://
  world_size: 1
  rank: 0
  gpu: 0

model_name: encoder_vqvae
model:
  seq_len: 2250
  num_leads: 12
  latent_dim: 128
  num_embeddings: 512  # Increased from 64
  commitment_cost: 0.1  # Reduced from 0.25
  pretrained_encoder_path: /Users/tenebrissilvam/Code/smiles_2025/ST-MEM/weights/st_mem_vit_base_encoder.pth

dataset:
  index_dir: /Users/tenebrissilvam/Code/smiles_2025/data/a-large-scale-12-lead-electrocardiogram-database-for-arrhythmia-study-1.0.0/
  ecg_dir: /Users/tenebrissilvam/Code/smiles_2025/data/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/records500_processed
  train_csv: /Users/tenebrissilvam/Code/smiles_2025/data/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/index_GENERAL_DIAGNOSIS_train_train.csv
  valid_csv: /Users/tenebrissilvam/Code/smiles_2025/data/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/index_GENERAL_DIAGNOSIS_train_val.csv
  test_csv: /Users/tenebrissilvam/Code/smiles_2025/data/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/index_GENERAL_DIAGNOSIS_val.csv
  filename_col: RELATIVE_FILE_PATH
  fs_col: SAMPLE_RATE
  fs: 250
  lead: 12lead
  label_col: GENERAL_DIAGNOSIS
  label_dtype: long
  train_transforms:
    - center_crop:
        crop_length: 2250
    - standardize
  eval_transforms:
    - center_crop:
        crop_length: 2250
    - standardize

dataloader:
  batch_size: 64
  num_workers: 8
  pin_memory: true

train:
  epochs: 20
  lr: 1e-4  # Reduced from 5e-4
  blr: 1e-4  # Reduced from 5e-4
  min_lr: 1e-6
  warmup_epochs: 5  # Reduced from 10
  weight_decay: 0.05
  accum_iter: 1
  optimizer: adamw
  use_amp: true
